# This file contains values from Cookiecutter

default_context:
  project_name: "desci"
  project_description: "`desci` is the Python cli/package for Decentralized Science by CrunchDAO"
  organization: "CrunchDAO"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "crunchdao"
  email: "placeholder@crunchdao.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
