name: desci

on:
  push:
    branches:
    - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build PDF and HTML paper
      run: |
        docker pull crunchdao/desci-pandoc
        docker run --rm -v $PWD/paper:/paper crunchdao/desci-pandoc paper.md -s --mathml --data-dir=./data/  --resource-path=./figures/ --bibliography ./paper.bib -o paper.pdf

    - name: Save Artifact
      uses: actions/upload-artifact@v3
      with:
        name: paper
        path: |
          paper/paper.pdf
