name: desci

on: [pull_request, push] # remove push if working. 

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4.2.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Build PDF and HTML paper
      run: |
        cd paper
        sudo apt-get -y install pandoc
        sudo apt-get install pandoc-citeproc
        sudo apt-get install texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra
        pandoc paper.md -s --mathml --data-dir=./data/  --resource-path=./figures/ --bibliography ./paper.bib -o paper.html
        pandoc paper.md -s --mathml --data-dir=./data/  --resource-path=./figures/ --bibliography ./paper.bib -o paper.pdf
    - name: Save Artifact
      uses: actions/upload-artifact@v3
      with:
        name: paper
        path: |
          paper/paper.html
          paper/paper.pdf
